sudo: required

language: python

python:
  - "3.6"

cache: pip

before_install:
  - sudo apt-get update
  - sudo apt-get install -y radare2 build-base linux-headers
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt

script:
  - python Tests/test_unpacker.py