sudo: required

language: python

python:
  - '3.6'
cache: pip

before_install:
  - pip install --upgrade pip setuptools pytest
  - pip install -r requirements.txt

script:
  - python -m pytest -s

deploy:
  provider: pypi
  user: Masrepus
  password:
    secure: jmlsP5GjRg92yVmsjcnqizqu5G56aeey2jF6bD32/RU5sIligjNNobYbDGPPH4UWyZ73/D2aa81FwAtXxR76On367QhIxK4pQUyyAPuhaF7/IRxN1LA9rXg98r+43QkuphdDPLP3hI3n4TxXMV2cfJcDmyeb5HA0BRtjeTAa5clLw3fJ8/MKzo9EHdzy2JNo2ACR23Fzd8E4hqcTvasl4rn8bqOcw7O6/gVNvCV2xx9lEMScyGQk22zqFDMEXDk4usDISO6ZGz/BUrBLL5PxBS1RXlE0Phj+QedMUSg0rIivuz2Zep/uDx6rUkg2HWj7Ou6M/vthIYB6qyrBMhTgOctODQ0WaH8Q1gO7WwX8eWxhswRCYm0FPCU8C7FhjuKJyiOqsBxitQKn+m2fiyc5yUBC9wsVr3JbjxLNyFeVv8K7o5kU7Pr4GcM0VyjUcZwDIP51ZLFtkDv50HoU8wGo5JrgtxjYmroLIJFmSmsI9uZiBfQgomwd+eAWe+bf7fWH4+RAz/qXY6g4wEk7szw7kTCXC15bjdSYwZRFCWQwZF1rmTUapmYCzeH0QQUO6LBnfWDfb+IUSmdiXNGf458uNUdhl0maPpb0qkRjGBNvxElPy1IdbcZRP1RPe7cFJ1UXiuYhY6hF5cIY/GOKR9woQzavKTUw4gaAUX2jOC9DzHA=
  on:
    tags: true
    all_branches: true
